export const vistasContenidos = [
  {
    number: 1010,
    key: 'inicio_estructura',
    title: 'Estructura',
    nombre_vista: 'InicioEstructura',
    label: 'Estructura',
    capitulo: 'Contexto',
    display: true,
  },
  {
    number: 1015,
    key: 'inicio',
    title: 'Inicio',
    nombre_vista: 'InicioView',
    label: 'Inicio',
    capitulo: 'Contexto',
    display: true,
  },
  {
    number: 1020,
    key: 'respuestas',
    title: 'Respuestas',
    nombre_vista: 'RespuestasView',
    label: 'Respuestas',
    capitulo: 'Contexto',
    display: true,
  },
  {
    number: 1025,
    key: 'que_buscamos_1',
    title: 'Qué buscamos 1',
    nombre_vista: 'QueBuscamos1View',
    label: 'Qué buscamos',
    capitulo: 'Contexto',
    display: false,
  },
  {
    number: 1030,
    key: 'primer_hallazgo',
    title: 'Primer hallazgo',
    nombre_vista: 'PrimerHallazgo',
    label: 'Primer hallazgo',
    capitulo: 'Hallazgos',
    display: true,
  },
  {
    number: 1035,
    key: 'segundo_hallazgo',
    title: 'Segundo hallazgo',
    nombre_vista: 'SegundoHallazgo',
    label: 'Segundo hallazgo',
    capitulo: 'Hallazgos',
    display: true,
  },
  {
    number: 1040,
    key: 'tercer_hallazgo',
    title: 'Tercer hallazgo',
    nombre_vista: 'TercerHallazgo',
    label: 'Tercer hallazgo',
    capitulo: 'Hallazgos',
    display: true,
  },
  {
    number: 1045,
    key: 'motociclistas',
    title: 'Motociclistas',
    nombre_vista: 'MotociclistasView',
    label: 'Motociclistas',
    capitulo: 'Motociclistas',
    display: true,
  },
  {
    number: 1050,
    key: 'motociclistas_b',
    title: 'Motociclistas (2)',
    nombre_vista: 'MotociclistasBView',
    label: 'Motociclistas (2)',
    capitulo: 'Motociclistas',
    display: true,
  },
  {
    number: 1055,
    key: 'motociclistas_implementaciones',
    title: 'Motociclistas (3)',
    nombre_vista: 'MotociclistasImplementaciones',
    label: 'Motociclistas (3)',
    capitulo: 'Motociclistas',
    display: true,
  },
  {
    number: 1060,
    key: 'empatia_a',
    title: 'Empatía (1)',
    nombre_vista: 'EmpatiaA',
    label: 'Empatía (1)',
    capitulo: 'Empatía',
    display: true,
  },
  {
    number: 1065,
    key: 'empatia_b',
    title: 'Empatía (2)',
    nombre_vista: 'EmpatiaB',
    label: 'Empatía (2)',
    capitulo: 'Empatía',
    display: true,
  },
  {
    number: 1070,
    key: 'empatia_c',
    title: 'Empatía (3)',
    nombre_vista: 'EmpatiaC',
    label: 'Empatía (3)',
    capitulo: 'Empatía',
    display: true,
  },
  {
    number: 1075,
    key: 'laboratorios_a',
    title: 'Laboratorios (1)',
    nombre_vista: 'LaboratoriosA',
    label: 'Laboratorios (1)',
    capitulo: 'Laboratorios',
    display: true,
  },
  {
    number: 1080,
    key: 'laboratorios_b',
    title: 'Laboratorios (2)',
    nombre_vista: 'LaboratoriosB',
    label: 'Laboratorios (2)',
    capitulo: 'Laboratorios',
    display: true,
  },
  {
    number: 1085,
    key: 'laboratorios_c',
    title: 'Laboratorios (3)',
    nombre_vista: 'LaboratoriosC',
    label: 'Laboratorios (3)',
    capitulo: 'Laboratorios',
    display: true,
  },
  {
    number: 1090,
    key: 'escuela_multiplicadores',
    title: 'Escuela de Multiplicadores',
    nombre_vista: 'EscuelaMultiplicadores',
    label: 'Escuela de Multiplicadores',
    capitulo: 'Escuela de Multiplicadores',
    display: true,
  },
  {
    number: 1095,
    key: 'aprendizajes_a',
    title: 'Aprendizajes (1)',
    nombre_vista: 'AprendizajesA',
    label: 'Aprendizajes (1)',
    capitulo: 'Aprendizajes',
    display: true,
  },
]
